local platform = getgenv().CrystalLevPlatform
local Theme = platform.Theme

function platform.GenerateCode(project)
    local code = [[
-- 💎 Generated by CrystaLev Platform
-- Hub: ]] .. project.Name .. [[
-- Author: ]] .. project.Author .. [[

if getgenv().]] .. project.Name .. [[ then return end
getgenv().]] .. project.Name .. [[ = true

local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")
local CoreGui = game:GetService("CoreGui")
local RunService = game:GetService("RunService")

local Player = Players.LocalPlayer
local PlayerGui = Player:WaitForChild("PlayerGui")

local function GetContainer()
    local s, r = pcall(function()
        if gethui then return gethui() end
        if syn and syn.protect_gui then syn.protect_gui(PlayerGui); return PlayerGui end
        return CoreGui
    end)
    return (s and r) and r or CoreGui
end

local Container = GetContainer()
for _, v in pairs(Container:GetChildren()) do
    if v.Name == "]] .. project.Name .. [[_Hub" then v:Destroy() end
end

local function Protect(obj)
    pcall(function() if syn and syn.protect_gui then syn.protect_gui(obj) end end)
end

local function Create(class, props)
    local obj = Instance.new(class)
    for k, v in pairs(props or {}) do
        if k == "Children" then for _, c in pairs(v) do c.Parent = obj end
        elseif k == "Parent" then obj.Parent = v
        else pcall(function() obj[k] = v end) end
    end
    Protect(obj)
    return obj
end

local function TweenObj(obj, time, props)
    local t = TweenService:Create(obj, TweenInfo.new(time, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), props)
    t:Play()
    return t
end

local function MakeDraggable(frame, dragObj)
    dragObj = dragObj or frame
    local drag, sp, sm
    dragObj.InputBegan:Connect(function(i)
        if i.UserInputType == Enum.UserInputType.MouseButton1 then
            drag = true; sp = frame.Position; sm = i.Position
        end
    end)
    UserInputService.InputChanged:Connect(function(i)
        if drag and i.UserInputType == Enum.UserInputType.MouseMovement then
            local d = i.Position - sm
            frame.Position = UDim2.new(sp.X.Scale, sp.X.Offset + d.X, sp.Y.Scale, sp.Y.Offset + d.Y)
        end
    end)
    UserInputService.InputEnded:Connect(function(i)
        if i.UserInputType == Enum.UserInputType.MouseButton1 then drag = false end
    end)
end

local Accent = Color3.fromRGB(]] .. math.floor(Theme.Accent.R * 255) .. [[, ]] .. math.floor(Theme.Accent.G * 255) .. [[, ]] .. math.floor(Theme.Accent.B * 255) .. [[)

local ScreenGui = Create("ScreenGui", { Name = "]] .. project.Name .. [[_Hub", Parent = Container })

local Main = Create("Frame", {
    Name = "Main",
    Size = UDim2.new(0, 550, 0, 380),
    Position = UDim2.new(0.5, -275, 0.5, -190),
    BackgroundColor3 = Color3.fromRGB(18, 18, 18),
    BorderSizePixel = 0,
    Parent = ScreenGui,
})

local TitleBar = Create("Frame", {
    Name = "TitleBar",
    Size = UDim2.new(1, 0, 0, 35),
    BackgroundColor3 = Color3.fromRGB(28, 28, 28),
    BorderSizePixel = 0,
    Parent = Main,
})

Create("TextLabel", {
    Name = "Title",
    Size = UDim2.new(1, -70, 1, 0),
    Position = UDim2.new(0, 10, 0, 0),
    BackgroundTransparency = 1,
    Text = "💎 ]] .. project.Name .. [[",
    TextColor3 = Accent,
    Font = Enum.Font.GothamBold,
    TextSize = 14,
    TextXAlignment = Enum.TextXAlignment.Left,
    Parent = TitleBar,
})

Create("TextLabel", {
    Name = "Credit",
    Size = UDim2.new(0, 60, 1, 0),
    Position = UDim2.new(1, -65, 0, 0),
    BackgroundTransparency = 1,
    Text = "CrystalLev",
    TextColor3 = Color3.fromRGB(80, 80, 80),
    Font = Enum.Font.Gotham,
    TextSize = 10,
    Parent = TitleBar,
})

MakeDraggable(Main, TitleBar)

local TabBar = Create("Frame", {
    Name = "TabBar",
    Size = UDim2.new(0, 130, 1, -35),
    Position = UDim2.new(0, 0, 0, 35),
    BackgroundColor3 = Color3.fromRGB(22, 22, 22),
    BorderSizePixel = 0,
    Parent = Main,
})

Create("UIListLayout", {
    Padding = UDim.new(0, 2),
    Parent = TabBar,
})

local ContentArea = Create("Frame", {
    Name = "Content",
    Size = UDim2.new(1, -135, 1, -40),
    Position = UDim2.new(0, 135, 0, 35),
    BackgroundColor3 = Color3.fromRGB(18, 18, 18),
    BorderSizePixel = 0,
    Parent = Main,
})

Create("UIListLayout", {
    Padding = UDim.new(0, 4),
    Parent = ContentArea,
})

local openedTab = nil
]]

    for _, tab in pairs(project.Tabs) do
        local tName = tab.Name:gsub("[^%w]", "_")
        
        code = code .. [[

-- Tab: ]] .. tab.Name .. [[
local TabBtn_]] .. tName .. [[ = Create("TextButton", {
    Name = "]] .. tName .. [[",
    Size = UDim2.new(1, -10, 0, 30),
    Position = UDim2.new(0, 5, 0, 0),
    BackgroundColor3 = Color3.fromRGB(28, 28, 28),
    TextColor3 = Color3.fromRGB(255, 255, 255),
    Text = "]] .. tab.Name .. [[",
    Font = Enum.Font.Gotham,
    TextSize = 12,
    BorderSizePixel = 0,
    Parent = TabBar,
})

local TabContent_]] .. tName .. [[ = Create("Frame", {
    Name = "]] .. tName .. [[_Content",
    Size = UDim2.new(1, 0, 1, 0),
    BackgroundTransparency = 1,
    Visible = false,
    Parent = ContentArea,
})

local Section_]] .. tName .. [[ = Create("Frame", {
    Name = "Section",
    Size = UDim2.new(1, -20, 0, 25),
    Position = UDim2.new(0, 10, 0, 0),
    BackgroundColor3 = Color3.fromRGB(28, 28, 28),
    BorderSizePixel = 0,
    Parent = TabContent_]] .. tName .. [[,
})

Create("TextLabel", {
    Size = UDim2.new(1, -16, 1, 0),
    Position = UDim2.new(0, 8, 0, 0),
    BackgroundTransparency = 1,
    Text = "]] .. tab.Name .. [[",
    TextColor3 = Accent,
    Font = Enum.Font.GothamBold,
    TextSize = 12,
    TextXAlignment = Enum.TextXAlignment.Left,
    Parent = Section_]] .. tName .. [[,
})
]]

        for _, el in pairs(tab.Elements) do
            local eName = el.Name:gsub("[^%w]", "_")
            
            if el.Type == "Button" then
                code = code .. [[
Create("TextButton", {
    Name = "]] .. eName .. [[",
    Size = UDim2.new(1, -20, 0, 28),
    Position = UDim2.new(0, 10, 0, 0),
    BackgroundColor3 = Color3.fromRGB(38, 38, 38),
    TextColor3 = Color3.fromRGB(255, 255, 255),
    Text = "]] .. el.Name .. [[",
    Font = Enum.Font.Gotham,
    TextSize = 12,
    BorderSizePixel = 0,
    Parent = TabContent_]] .. tName .. [[,
}).MouseButton1Click:Connect(function()
    ]] .. (el.Script or "") .. [[
end)
]]
            elseif el.Type == "Toggle" then
                code = code .. [[
local ToggleFrame_]] .. eName .. [[ = Create("Frame", {
    Name = "]] .. eName .. [[",
    Size = UDim2.new(1, -20, 0, 30),
    Position = UDim2.new(0, 10, 0, 0),
    BackgroundColor3 = Color3.fromRGB(38, 38, 38),
    BorderSizePixel = 0,
    Parent = TabContent_]] .. tName .. [[,
})

Create("TextLabel", {
    Size = UDim2.new(0, 150, 1, 0),
    Position = UDim2.new(0, 8, 0, 0),
    BackgroundTransparency = 1,
    Text = "]] .. el.Name .. [[",
    TextColor3 = Color3.fromRGB(255, 255, 255),
    Font = Enum.Font.Gotham,
    TextSize = 12,
    TextXAlignment = Enum.TextXAlignment.Left,
    Parent = ToggleFrame_]] .. eName .. [[,
})

local ToggleBtn_]] .. eName .. [[ = Create("Frame", {
    Size = UDim2.new(0, 35, 0, 18),
    Position = UDim2.new(1, -43, 0.5, -9),
    BackgroundColor3 = Color3.fromRGB(60, 60, 60),
    BorderSizePixel = 0,
    Parent = ToggleFrame_]] .. eName .. [[,
})

local ToggleDot_]] .. eName .. [[ = Create("Frame", {
    Size = UDim2.new(0, 14, 0, 14),
    Position = UDim2.new(0, 2, 0.5, -7),
    BackgroundColor3 = Color3.fromRGB(255, 255, 255),
    BorderSizePixel = 0,
    Parent = ToggleBtn_]] .. eName .. [[,
})

local ToggleState_]] .. eName .. [[ = false
ToggleBtn_]] .. eName .. [[.InputBegan:Connect(function(i)
    if i.UserInputType == Enum.UserInputType.MouseButton1 then
        ToggleState_]] .. eName .. [[ = not ToggleState_]] .. eName .. [[
        TweenObj(ToggleBtn_]] .. eName .. [[, 0.2, {BackgroundColor3 = ToggleState_]] .. eName .. [[ and Accent or Color3.fromRGB(60, 60, 60)})
        TweenObj(ToggleDot_]] .. eName .. [[, 0.2, {Position = UDim2.new(0, ToggleState_]] .. eName .. [[ and 19 or 2, 0.5, -7)})
        ]] .. (el.Script or "") .. [[
    end
end)
]]
            elseif el.Type == "Slider" then
                code = code .. [[
local SliderFrame_]] .. eName .. [[ = Create("Frame", {
    Name = "]] .. eName .. [[",
    Size = UDim2.new(1, -20, 0, 45),
    Position = UDim2.new(0, 10, 0, 0),
    BackgroundColor3 = Color3.fromRGB(38, 38, 38),
    BorderSizePixel = 0,
    Parent = TabContent_]] .. tName .. [[,
})

local SliderLabel_]] .. eName .. [[ = Create("TextLabel", {
    Size = UDim2.new(1, -16, 0, 18),
    Position = UDim2.new(0, 8, 0, 3),
    BackgroundTransparency = 1,
    Text = "]] .. el.Name .. [[" .. ]] .. (el.Min or 1) .. [[,
    TextColor3 = Color3.fromRGB(255, 255, 255),
    Font = Enum.Font.Gotham,
    TextSize = 11,
    TextXAlignment = Enum.TextXAlignment.Left,
    Parent = SliderFrame_]] .. eName .. [[,
})

local SliderBar_]] .. eName .. [[ = Create("Frame", {
    Size = UDim2.new(1, -16, 0, 4),
    Position = UDim2.new(0, 8, 0, 30),
    BackgroundColor3 = Color3.fromRGB(60, 60, 60),
    BorderSizePixel = 0,
    Parent = SliderFrame_]] .. eName .. [[,
})

local SliderFill_]] .. eName .. [[ = Create("Frame", {
    Size = UDim2.new(0, 0, 1, 0),
    BackgroundColor3 = Accent,
    BorderSizePixel = 0,
    Parent = SliderBar_]] .. eName .. [[,
})

local SliderValue_]] .. eName .. [[ = ]] .. (el.Min or 1) .. [[
local SliderDrag_]] .. eName .. [[ = false
SliderBar_]] .. eName .. [[.InputBegan:Connect(function(i)
    if i.UserInputType == Enum.UserInputType.MouseButton1 then
        SliderDrag_]] .. eName .. [[ = true
    end
end)
UserInputService.InputEnded:Connect(function(i)
    if i.UserInputType == Enum.UserInputType.MouseButton1 then SliderDrag_]] .. eName .. [[ = false end
end)
UserInputService.InputChanged:Connect(function(i)
    if SliderDrag_]] .. eName .. [[ and i.UserInputType == Enum.UserInputType.MouseMovement then
        local pct = math.clamp((i.Position.X - SliderBar_]] .. eName .. [[.AbsolutePosition.X) / SliderBar_]] .. eName .. [[.AbsoluteSize.X, 0, 1)
        SliderValue_]] .. eName .. [[ = math.floor(]] .. (el.Min or 1) .. [[ + (]] .. (el.Max or 100) .. [[ - ]] .. (el.Min or 1) .. [[) * pct)
        SliderFill_]] .. eName .. [[.Size = UDim2.new(pct, 0, 1, 0)
        SliderLabel_]] .. eName .. [[.Text = "]] .. el.Name .. [[: " .. SliderValue_]] .. eName .. [[
        ]] .. (el.Script or "") .. [[
    end
end)
]]
            end
        end
        
        code = code .. [[
TabBtn_]] .. tName .. [[.MouseButton1Click:Connect(function()
    if openedTab then openedTab.Visible = false end
    TabContent_]] .. tName .. [[.Visible = true
    openedTab = TabContent_]] .. tName .. [[
end)
]]
    end
    
    code = code .. [[
-- Открыть первую вкладку
if TabBtn_]] .. (project.Tabs[1] and project.Tabs[1].Name:gsub("[^%w]", "_") or "") .. [[ then
    TabBtn_]] .. (project.Tabs[1] and project.Tabs[1].Name:gsub("[^%w]", "_") or "") .. [[.MouseButton1Click:Connect(function() end)
    TabBtn_]] .. (project.Tabs[1] and project.Tabs[1].Name:gsub("[^%w]", "_") or "") .. [[:Clone().MouseButton1Click:Fire()
end
]]
    
    return code
end
